name: "Edge Buildx Builder"
description: "Pushes built artifacts to Docker"

inputs:
 image_name:
   description: “Name of container to build”
   required: true
 registry_username:
   description: “Username for image registry”
   required: true
 registry_password:
   description: “Password for image registry”
   required: true
 docker_context:
   description: “Context for docker build”
   required: false
   default: "."
 docker_file:
   description: “Dockerfile path”
   required: false
   default: "Dockerfile"
 platforms:
   description: “Target build architectures”
   required: false
   default: "linux/amd64,linux/arm64"
 publish:
   description: “Publish to container registry”
   required: false
   default: true

runs:
 using: "composite"
 steps:
    - uses: docker/metadata-action@v3      
      id: meta 
      with:
        images: |
            ${{inputs.image_name}}
        tags: |
            type=ref,event=pr,prefix=pull-request-
            type=ref,event=tag
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) && !startsWith(github.event_name, 'workflow_dispatch') }}
            type=ref,event=branch,enable=${{ !endsWith(github.ref, github.event.repository.default_branch) && !startsWith(github.event_name, 'workflow_dispatch') }}
            type=raw,value=${{github.actor}}-{{branch}}-{{sha}},enable=${{ startsWith(github.event_name, 'workflow_dispatch') }},priority=1000
            type=sha,priority=100
        flavor: |
            latest=false

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}

    - uses: docker/build-push-action@v2
      with:
        context: ${{inputs.docker_context}}
        platforms: ${{inputs.platforms}}
        push: ${{inputs.publish}}
        file: ${{inputs.docker_file}}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
